
# futility monitoring and dose comparison for interim and final analysis
todo2 <- function(ic12, fdata, ia.post,fa.post1, fa.post2, fa.post3,  post,
                  ia.mean, fa.mean1, fa.mean2, fa.mean3, 
                  ntrial, peff, theta0, delta1, ia12, idr.m, wl){
  
  SEL <- matrix(0,ncol=length(peff),nrow=ntrial)
  FUTILE <- array(0,c(2,length(peff),ntrial))
  inconclusive <- matrix(1,ncol=length(peff),nrow=ntrial)
  fa.mean <- matrix(0,ncol=length(peff),nrow=ntrial)
  
  ## all posible cutoff combinations for futility monitoring
  a12 <- NULL
  for(ia1 in 1:98){ for(ia2 in max(51,ia1):99){a12 <- rbind(a12,c(ia1,ia2)/100)} }
  a1 <- a12[ia12,1];a2 <- a12[ia12,2]
  
  ## all posible cutoff combinations for non-inferior comparison
  c12 <- NULL
  for(ic1 in 1:98){ for(ic2 in ic1:min(ic1+60,99)){c12 <- rbind(c12,c(ic1,ic2)/100)} }
  c1 <- c12[ic12,1];c2 <- c12[ic12,2]
  
  ## making desicions for the simulated trials generated by function 'todo2_data_generation()'
  for(trial in 1:ntrial){
    
    ## interim analysis
    setI <- 1:2     ## doses passed the interim futility monitoring
    exclude <- NULL ## doses failed to pass the interim futility monitoring
    if(ia.post[trial,2]<a1){ setI <- NULL;exclude <- 1:2
    }else if(ia.post[trial,1]<a1){ setI <- 2;exclude <- 1  }
    
    if(length(exclude)>0){
      inconclusive[trial,exclude] <- -2
      FUTILE[1,exclude,trial] <- FUTILE[2,exclude,trial] <- 1
      fdata[exclude,3:4,trial] <- 0
      fdata[exclude,5:6,trial] <- fdata[exclude,1:2,trial]
    }
    if(length(exclude)==length(peff)){fa.mean[trial, ] <- ia.mean[trial, ]; next}
    
    ## final analysis
    setII <- setI    ## doses passed the final futility monitoring
    exclude <- NULL  ## doses failed to pass the final futility monitoring
    
    if(length(setI)==2){
      fa.mean[trial, ] <- fa.mean1[trial, ]
      setII <- which(ia.post[trial,]>=a1 & fa.post1[trial,]>=a2)
      exclude <- which(ia.post[trial,]<a1 | (ia.post[trial,]>=a1 & fa.post1[trial,]<a2))
    }
    
    ## futility monitoring at the final analysis
    if(length(setI)==1){ # only one dose is effective
      if(setI==1){
        fa.mean[trial, ] <- fa.mean3[trial, ]
        if(fa.post3[trial,1]>=a2){
          setII <- 1; exclude <- 2
        }else{ setII <- NULL; exclude <- c(1,2) }
      }
      if(setI==2){ # both doses are effective
        fa.mean[trial, ] <- fa.mean2[trial, ]
        if(fa.post2[trial,2]>=a2){
          setII <- 2; exclude <- 1
        }else{  setII <- NULL;exclude <- c(1,2) }
      }
    }
    
    if(length(exclude)>0){
      inconclusive[trial,exclude] <- -2
      FUTILE[2,exclude,trial] <- 1
    }
    
    if(length(exclude)==length(peff)){next}
    
    ## decision-making at the final analysis
    if(length(setII)==1){ # only one dose is effective
      SEL[trial,setII] <- SEL[trial,setII] + 1
    }else{ # both doses are effective
      if(post[trial]<c1){ # inferior
        SEL[trial,2] <- SEL[trial,2] + 1;inconclusive[trial,1] <- 0
      }else if(post[trial]>c1 & post[trial]<c2){ # inconclusive
        inconclusive[trial,1] <- -1 
      }else{ # non-inferior
        SEL[trial,1] <- SEL[trial,1] + 1 }
    }
  }
  
  sel <- colMeans(SEL)
  pts <- apply(fdata,c(1,2),mean)
  
  futile <- apply(FUTILE,c(1,2), mean)*100
  colnames(futile) <- c('arm1','arm2');rownames(futile) <- c('IA','FA')
  
  none <- mean(colSums(FUTILE[2,,])==2)*100
  gpower <- 0
  for(trial in 1:ntrial){
    if( sum(FUTILE[2,,trial]==(peff<theta0)) ){gpower <- gpower + 100/ntrial}
  }
  
  inc <- mean(inconclusive[,1]==-1)*100
  inc <- t(as.matrix(inc))
  colnames(inc) <- c('inc.d1')
  
  # present0 <- c(sel*100,sum(inc),pts[,6],none)
  present0 <- c(sel*100,sum(inc),none,pts[,6])
  IDR <- sum(present0*idr.m)
  weighted_loss <- sum(inc)*wl+IDR
  if(sum(peff<=theta0)==length(peff)){weighted_loss <- IDR}
  present <- c(sel*100,sum(inc),IDR,weighted_loss,pts[,6],none)
  present <- t(as.matrix(present))
  colnames(present) <- c('arm1','arm2','inc','IDR','weighted_loss','ASS1','ASS2','none')
  
  parameter <- c(a1,a2,c1,c2)
  parameter <- t(as.matrix(parameter))
  colnames(parameter) <- c('a1','a2','c1','c2')
  
  ## bias and MSE
  bias <- mse <- rep(0, length(peff))
  for(id in 1:length(peff)){
    bias[id] <- mean(fa.mean[,id] - peff[id])
    mse[id] <- mean((fa.mean[,id] - peff[id])^2)
  }
  
  result.list <- list(peff=peff, pts=round(pts,2), parameter=parameter,
                      futile=round(futile,2), present=present,
                      bias = bias, mse = mse)
  return(result.list)
}